### ISSUE TITLE
Unnecessary space

### ISSUE THREAD

**Issue by alexclassroom** [terrylinooo/mynote#11]
**Describe the bug**
Unnecessary space in inc\customer\about.php line 25.

**To Reproduce**
1. Open inc\customer\about.php.
2. Go to line 25.
3. Review `$about .= '<br /><br /><a href="' . esc_url( 'https://github.com/terrylinooo/mynote ') . '">https://github.com/terrylinooo/mynote</a>';`
4. This uncessary space makes the link failed.

**Expected behavior**
No unnecessary space in this line and URL works well.

**Comment by terrylinooo** [comment]
謝謝回報...難怪都沒流量進來這個 git repository @@

**Comment by alexclassroom** [comment]
我意外發現的。

有個其他社團的朋友在詢問這個佈景主題頁首內建標籤雲的問題，我本來請他自己來這問，後來我自己點了佈景主題中的連結，才發現多了一個不需要的半形空格，而且還會導致連線到不存在的頁面 (多了 %20)。
