### ISSUE TITLE
Footer style issues on smaller devices after v1.3.3

### ISSUE THREAD

**Issue by hacheraw** [terrylinooo/mynote#12]
After 1.3.3 update, while using:
- mynote_nav( 'footer' )
- mynote_nav( 'social' )
footer is not longer responsive. [**video here**](https://notes.jorgeff.com/img/bug12.mp4)

Also, I prefer the copyright to be at the bottom but it's up to you:
![imagen](https://user-images.githubusercontent.com/10481749/56157466-7a7a4c80-5fb7-11e9-8e3d-562c207ed892.png)

**Comment by terrylinooo** [comment]
I will fix it today and add a new customizer setting to allow user to choose the prefferred location.

**Comment by terrylinooo** [comment]
Waiting for update.
