### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by mauromascarenhas** [terrylinooo/mynote#14]
Could you add the portuguese translation into your theme, please?
I've just finished its translation (see attached files [po and mo]).

[mynote-pt_BR.zip](https://github.com/terrylinooo/mynote/files/3213256/mynote-pt_BR.zip)

**Comment by terrylinooo** [comment]
Ok. Thank you very much for the translation.

**Comment by mauromascarenhas** [comment]
Sorry, but you've forgotten to rename it to pt_BR (I was using mynote-pt_BR for global availability ([wp-content/translation/themes']).
If you leave the name like that the translation will not work.

**Comment by terrylinooo** [comment]
Got it. Thank you.
