### ISSUE TITLE
文章页上的作者卡片 为什么不显示头像呢

### ISSUE THREAD

**Issue by jonasli** [terrylinooo/mynote#15]
![image](https://user-images.githubusercontent.com/9443954/59808361-8a533b80-932e-11e9-8cda-53df24e253ac.png)
![image](https://user-images.githubusercontent.com/9443954/59808409-afe04500-932e-11e9-9c19-0161225f146e.png)

**Comment by terrylinooo** [comment]
那是使用 wordpress.com 的 gravatar. 您必須到這裡註冊
https://en.gravatar.com/
