### ISSUE TITLE
Add german translation (de_DE)

### ISSUE THREAD

**Issue by Pandiora** [terrylinooo/mynote#17]
I found your WP-theme in the comments on [Quora](https://www.quora.com/Which-is-the-best-WordPress-theme-for-a-programming-blog). It was exactly what I was searching for and maybe I can give you something back, by adding another translation. Thx for your efforts.

[mynote-de_DE.zip](https://github.com/terrylinooo/mynote/files/3388941/mynote-de_DE.zip)

Cheers o7

**Comment by terrylinooo** [comment]
Thank you.
