### ISSUE TITLE
Wrapping all functions from inc/template-* in function_exists()

### ISSUE THREAD

**Issue by KyrietS** [terrylinooo/mynote#18]
I've created a child theme from **Mynote** and some parts of the original theme are **impossible to modify or replace**. There are many functions inside `inc/` folder that generate some kind of HTML. 

The only way to modify structures generated in those functions is to **fork this whole theme repo** which is not the best solution in most cases. Especially when I just want to make some **minor changes** to `mynote_author_posted_date` function (I can't do that through WP child theme system).

Are there any reasons against wrapping all functions in `function_exists()`?

Thanks

**Comment by terrylinooo** [comment]
Thanks for your feedback.

I take your suggestions and is about to update in version 1.4.0
