### ISSUE TITLE
Invalid image display

### ISSUE THREAD

**Issue by Maximal1988** [terrylinooo/mynote#20]
I installed your theme for WP yesterday. There is a problem with the header image at the top. I have a 5k display and if I open the browser window in full screen, a part of the new image appears. The resolution of the picture is maximum. Is it possible to fix this somehow?
https://www.dropbox.com/s/35l8t1ov45dkhk1/wp.mov?dl=0
Tested on Imac 27" 5k

**Comment by terrylinooo** [comment]
That is because your screen resolution's width is more than 1920.
Please update your Mynote version to 1.4.1 to fix this issue.
