### ISSUE TITLE
希望能支持简体中文

### ISSUE THREAD

**Issue by 547176052** [terrylinooo/mynote#21]
希望能支持简体中文

**Comment by Nebula-zyx** [comment]
本来就可以支持啊，我用的就是简体中文啊，你没看作者主页么，他是台湾大佬

**Comment by liangshuai19** [comment]
他的首页有下载选项是怎么设置的？

**Comment by liangshuai19** [comment]
> 本来就可以支持啊，我用的就是简体中文啊，你没看作者主页么，他是台湾大佬

开发者的Mynote主题首页有下载选项是怎么设置的呢？我找了好久都没找到。能不能指点一下。

**Comment by liangshuai19** [comment]
要怎么开通？

**Comment by liangshuai19** [comment]
我需要这个功能，要怎么实现？

**Comment by Nebula-zyx** [comment]
用HTML把媒体路径弄上就好了
2020年9月30日 12:41于 liangshuai19 <notifications@github.com>写道：

我需要这个功能，要怎么实现？
