### ISSUE TITLE
No site title except home

### ISSUE THREAD

**Issue by Li-An** [terrylinooo/mynote#26]
**Is your feature request related to a problem? Please describe.**
Hello, I suppose it’s a strong design choice but there is no site’s title if the user is not on home page. So, they may come though a Google search, read the content and leave without knowing the name of the site. How to show the title eventually ?

**Describe the solution you'd like**
Show the title somewhere.

**Comment by terrylinooo** [comment]
It is better to define your own title rule in the SEO plugin that you are
using.

Li-An <notifications@github.com> 於 2019年11月12日 週二 上午1:02 寫道：

**Comment by Li-An** [comment]
Sorry, I don’t understand what your mean. The title of my site is L'Écho des Plugins WP (see https://www.echodesplugins.li-an.fr/) and the title does not show in the single pages (the SEO plugin is correctly configured.

**Comment by terrylinooo** [comment]
For example, I use Yoast SEO plugin and it has options for customizing page title:

![image](https://user-images.githubusercontent.com/11989371/68638994-31cf4580-053e-11ea-97c9-cc0435e322f2.png)

Take a look at your SEO plugin, it might have similar features.

**Comment by Li-An** [comment]
Sorry for my bad english: it was not about the "title" (SEO) but about the name of the site.
