### ISSUE TITLE
头像布局错误

### ISSUE THREAD

**Issue by Nebula-zyx** [terrylinooo/mynote#29]
**Describe the bug**

**To Reproduce**
1. 文章作者及发布日期中作者头像过大布局错误
2. 还有作者卡片同上述问题一样

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 1.5.1

**Smartphone (please complete the following information):**

**Additional context**

![批注 2019-12-03 055231](https://user-images.githubusercontent.com/41985658/69998996-96585000-1592-11ea-87ea-2a1e89593ed5.png)
![image](https://user-images.githubusercontent.com/41985658/69999223-18e10f80-1593-11ea-84b3-246f67d2b8a0.png)

**Comment by terrylinooo** [comment]
您的裝置看我的網站有無此問題:

https://terryl.in/en/highlight-js-html-code-language-list-for-syntax-highlighting/

如果沒有的話請關閉外掛測試是那一個外掛的 CSS 影響。

**Comment by Nebula-zyx** [comment]
哦哦，多謝大神，我去看看

**Comment by Nebula-zyx** [comment]
> 您的装置看我的网站有无此问题：
> 
> https://terryl.in/en/highlight-js-html-code-language-list-for-syntax-highlighting/
> 
> 如果没有的话请关闭外挂测试是那一个外挂的CSS影响。

應該就是我用了緩存插件開了CDN壓縮了css

**Comment by terrylinooo** [comment]
> 哦哦，多謝大神，我去看看

阿，不要叫我大神啦。我只是喜歡 coding 的平凡人。
後續有問題再詢問。
