### ISSUE TITLE
bad management of Markdown’s footnote

### ISSUE THREAD

**Issue by Li-An** [terrylinooo/mynote#30]
**Describe the bug**
When a footnote is created, the showing of the note is buggy (origin of the note and the footnote itself).

**To Reproduce**
Create a footnote in Markdown and see the result.

**Expected behavior**
Note must be entirely visible and same when going back to text.

**Screenshots**
https://ibb.co/R4k9Vbt
https://ibb.co/RCtBkQ6
https://ibb.co/3zSxHvd

See the note here https://www.echodesplugins.li-an.fr/tutoriaux/mon-premier-wordpress/#fnref-17358-bignote

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome and Opera
 - Version last

**Comment by MuTsunTsai** [comment]
Yes this should get fixed. For the time being, you can go to "Custom CSS" and add the following:
```css
* { scroll-margin-top: 50px; }
/* or whatever offset that works for you */
```

**Comment by Li-An** [comment]
Thanks a lot. I try this.
