### ISSUE TITLE
如何取消首页的分类目录显示？

### ISSUE THREAD

**Issue by playNoA** [terrylinooo/mynote#32]
抱歉，我翻遍了整个菜单，也没有找到对应的设置，你能告诉我吗？
![image](https://user-images.githubusercontent.com/7344597/76145644-4c699380-60c6-11ea-818f-2f52ef5f714d.png)
在哪个标签？
![image](https://user-images.githubusercontent.com/7344597/76145648-59868280-60c6-11ea-8528-265494904b00.png)
谢谢

**Comment by terrylinooo** [comment]
有放東西在頁首的 widget (小工具) 就會消失喔。那邊是預設首頁沒放自訂 widget 資訊的顯示。

**Comment by playNoA** [comment]
![image](https://user-images.githubusercontent.com/7344597/76156878-9f316280-613b-11ea-93be-97e624b20dfd.png)
谢谢，完美实现；你的作品很优秀，我使用了两个
