### ISSUE TITLE
文章卡片数量请教

### ISSUE THREAD

**Issue by Dvil404** [terrylinooo/mynote#39]
我在使用了mynote主题后，主页显示的文章卡片数量一直是2个，如下图所示，第三个文章无法在第一页显示（首页版面已设置成3个一行），我想设置成https://terryl.in/zh/    下方的文章数量样式，希望得到您的帮助
![image](https://user-images.githubusercontent.com/38025113/86430209-40b07580-bd24-11ea-8108-be3ad3b533de.png)

**Comment by terrylinooo** [comment]
您好。請問設定值是什麼呢?

![image](https://user-images.githubusercontent.com/11989371/86430705-87eb3600-bd25-11ea-9cc4-c7c9bdc4c979.png)

**Comment by Dvil404** [comment]
您是指什么的设定值？

**Comment by Dvil404** [comment]
这里我显示的是2，这个参数和我的显示数量问题有关么?

**Comment by Dvil404** [comment]
经过测试，确实是这个参数的问题，谢谢你
