### ISSUE TITLE
hi, it seems my featured image display Incorrectly in the post?

### ISSUE THREAD

**Issue by zs8861** [terrylinooo/mynote#4]
**Describe**
hi, it seems my featured image display Incorrectly in the post, but I see it's normal in your post.

[https://ipixelgames.com/](https://ipixelgames.com/)

**Screenshots**
![Imgur](https://i.imgur.com/hMYp9xL.png)
![Imgur](https://i.imgur.com/W7mUMBH.png)

**Comment by zs8861** [comment]
### I know how to do it, thank you;)

**Comment by terrylinooo** [comment]
@zs8861 

Could you share that about how you figure out the problem with me . Maybe other people meet the same issue too.

**Comment by zs8861** [comment]
I can only use the 600 x 250px size featured image, if I use other size's featured image, the post will display incorrect in the home page

**Comment by terrylinooo** [comment]
@zs8861 Thanks for your replying.
