### ISSUE TITLE
iPhone Safari Breadcrumbs rendering issue

### ISSUE THREAD

**Issue by Project-42** [terrylinooo/mynote#42]
I don't think this issue is exactly related to the Theme, but wonder if someone else see this estrange gray line when checking the blog in Safari for iPhone:
https://imgur.com/yOQd5ga

Android Chrome seems to be fine:
https://imgur.com/s7c3xGb

The Theme is amazing btw, hope to have website live with it next week :)

**Comment by terrylinooo** [comment]
The CSS gradient syntax doesn't support in mobile Safari, I will use other syntax to fix it. However, there is an option in  Theme customizer to remove the gradient mask.

**Comment by Project-42** [comment]
Thanks for the reply @terrylinooo 
Will wait for that "fix" :)
