### ISSUE TITLE
homepage is broken.

### ISSUE THREAD

**Issue by platanus-kr** [terrylinooo/mynote#46]
**Describe the bug**
homepage (front page) css is not applied. 
My theme version is 2.0.0

**To Reproduce**
Please visit [this website](http://skogur.net).

**Expected behavior**
It worked fine in previous versions.

**Screenshots**
<img width="658" alt="스크린샷 2021-03-14 오전 9 12 43" src="https://user-images.githubusercontent.com/6806008/111053243-77d74900-84a5-11eb-93cf-a9e1b49ad38f.png">

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all
 - Version: latest

**Comment by terrylinooo** [comment]
Sorry for that. I have updated and fixed it.
