### ISSUE TITLE
XSS vulnerable user inputs

### ISSUE THREAD

**Issue by SorinGFS** [terrylinooo/mynote#47]
**Describe the bug**
User inputs are not protected against XSS

**To Reproduce**
Try to inject XSS in user inputs, e.g. in `comment-body` insert `<script>alert('hacked')</script>`

**Expected behavior**
XSS protection

**How to solve the problem**
Wordpress provides a set of functions in order to achieve XSS protection, [see docs](https://codex.wordpress.org/Validating_Sanitizing_and_Escaping_User_Data).

**Comment by terrylinooo** [comment]
Will be fixed soon, thanks for your report.

**Comment by SorinGFS** [comment]
Thank you for solving it so fast, but this is not the right way, you just strip away all the html tags but some of them are usefull: `<b><strong><blockquote><q><abbr><u><i>` amd many more.... I think it should be an option somewhere in settings allowing the admin to decide which tags are allowed in comments.

Without such a setting options like the following would never exist:
![image](https://user-images.githubusercontent.com/25417015/112108139-7c43e600-8bb8-11eb-892a-0e3ca938775e.png)

And being on this chapter I must add that that allowed tags in comments should also do their job, for example if some text is marked with `<b>` it should appear ... **bold** on comments.

**Comment by SorinGFS** [comment]
And... since you are promoting the `WP Githuber MD` plugin (which I use) I think you should also allow markdown in comments if plugin is active. This would be a great feature of your theme.
