### ISSUE TITLE
All posts are showing up on one page

### ISSUE THREAD

**Issue by santhoshrajr** [terrylinooo/mynote#5]
**Bug Description**
It seems like pagination is not configurable in the Theme. All posts are showing up on page 1. I currently have 8 posts which are showing up on page 1. I expect it to be limited to 5 posts per page

**Reproduce**
1. Go to 'santhoshravirala.com'
2. Verify there are 8 posts
3. Scroll down to bottom and verify page number still shows 1

**Expected behavior**
Number of posts on the page should be configurable

**Screenshots**
![image](https://user-images.githubusercontent.com/14833988/54501655-edcb6880-48fc-11e9-8c28-8b73b8eef96c.png)

**Comment by terrylinooo** [comment]
Do you use static front page as your website's homepage?
I figure out that this issue happens on static front page. I will fix it today.

**Comment by santhoshrajr** [comment]
No I use the posts page as the home page

**Comment by terrylinooo** [comment]
@santhoshrajr 
Please update: https://wordpress.org/themes/mynote/

**Comment by santhoshrajr** [comment]
I don't see page widget completely now https://santhoshravirala.com. Am i missing something

**Comment by terrylinooo** [comment]
A page doesn't have sidebar widgets in this theme. If you need it, I can add it for you in next version.

**Comment by santhoshrajr** [comment]
Do you mean I need to remove the sidebar widget to see the page numbers

**Comment by terrylinooo** [comment]
Do you mean that the pagigantion is not showed on your homepage?

**Comment by santhoshrajr** [comment]
Yes.

**Comment by santhoshrajr** [comment]
Should i reopen this?

**Comment by terrylinooo** [comment]
I have no idea about your issue. I works fine on my website, so..
Did you update theme to the lastest 1.3.1?

Make sure you have configured the setting correctly. My site's configuration looks like this:

![image](https://user-images.githubusercontent.com/11989371/54575968-4a2fa480-4a31-11e9-8187-142e6cd803b0.png)

**Comment by santhoshrajr** [comment]
Thanks for sharing this. I couldn't find this setting before. It works now 👍 . You can close this
