### ISSUE TITLE
修改字体

### ISSUE THREAD

**Issue by zihluwang** [terrylinooo/mynote#52]
希望能提供文章字体自定义功能，默认字体显示有问题，无法清楚的辨认加粗字体与默认字体
![Pic](https://bucket.vorbote.cn/image/png/bLizlz-1618195478.png)

**Comment by skyroam** [comment]
好像主题里有字体的编码文件，估计可以替换

**Comment by skyroam** [comment]
说错了，那个不是字体，请问你解决了吗？@vorbote

**Comment by vorbote** [comment]
> 说错了，那个不是字体，请问你解决了吗？@vorbote

还没呢，对WordPress还不是很懂

**Comment by 2ipm1nd** [comment]
+1，我也想要知道怎麼自定義字體……，找了很久好像都沒人說明
