### ISSUE TITLE
Firefox: progress bar almost invisible

### ISSUE THREAD

**Issue by hacheraw** [terrylinooo/mynote#6]
**Describe the bug**
The progress bar is almost invisible.

**Expected behavior**
Maybe pick the colors from Personalize > Progress Bar > Color

**Screenshots**
I've changed the height so we can notice it:
![screenshot](https://notes.jorgeff.com/img/progress-bar.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Firefox
 - Version 66.0.2 64bits

**Additional context**
This may be a feature request instead of a bug.
I know how to change background color with css but can't figure how to change the bar color.

**Comment by terrylinooo** [comment]
Hello. Could you provide me your website's URL, I will check it.

Did you try to change border color?
![image](https://user-images.githubusercontent.com/11989371/55670594-0b1aa380-58b9-11e9-92c0-a231eb1da8fb.png)

**Comment by hacheraw** [comment]
# Google Chrome:
Works as expected:
![imagen](https://user-images.githubusercontent.com/10481749/55674080-97bc6600-58a7-11e9-8b44-246f31e4aad4.png)



# Firefox
Still the same :(
![imagen](https://user-images.githubusercontent.com/10481749/55673903-10222780-58a6-11e9-8bcb-664b587b1fb1.png)

BTW: The screenshot above is from your theme but I was using a homemade Child theme and just found this doesn't actually work as it should:
![imagen](https://user-images.githubusercontent.com/10481749/55673943-7c9d2680-58a6-11e9-8426-dcfa325658f7.png)


Anyway, **your theme is awesome**. I don't know if I should open a feature request or something, but how does Social menu work? Twitter, Instagram, gitHub and Facebook icons work great but is there anyway to insert Spotify or any other that is not on the list? Thanks!

**Comment by terrylinooo** [comment]
Thank you for replying. I have fixed it. I will update the theme soon.

**Comment by terrylinooo** [comment]
Thanks for reporting this issue. I have updated this theme to version 1.3.2
It will be updated on the WordPress theme dictionary soon.
