### ISSUE TITLE
Child theme

### ISSUE THREAD

**Issue by hacheraw** [terrylinooo/mynote#7]
**Is your feature request related to a problem? Please describe.**
I've made a Child theme but some things doesn't work.
![imagen](https://user-images.githubusercontent.com/10481749/55674182-db639f80-58a8-11e9-93e9-9f9c44f4cbe1.png)
![imagen](https://user-images.githubusercontent.com/10481749/55674194-ee766f80-58a8-11e9-9d23-0f77b25a769e.png)
![imagen](https://user-images.githubusercontent.com/10481749/55674197-02ba6c80-58a9-11e9-930b-624e7df94662.png)

**Describe the solution you'd like**
Including a Child-theme as this is an awesome theme for developers 

**Describe alternatives you've considered**
I can't find any alternative

**Additional context**
Also it would be nice to add features to the social menu. Like a tab under personalization where we can map font awesome icons to social menu names. For example: 'Spotify' => 'fab fa-spotify'

**Comment by terrylinooo** [comment]
Thanks for reporting this issue. I have updated this theme to version 1.3.2
It will be updated on the WordPress theme dictionary soon.
