### ISSUE TITLE
Post tags don't adjust to container div

### ISSUE THREAD

**Issue by hacheraw** [terrylinooo/mynote#8]
It's-a-me again!

**Describe the bug**
When there is a lot of post tags, they go all the way to the right. Some of them can't be clicked because they are under sidebar.

**To Reproduce**
1. Create new Post with a lot of tags
2. View/Preview post

**Expected behavior**
Adjust to container div
I don't know if this is the best way but it can be fixed this way:
- Adding float to `.tags a`:
```css
.tags a {
    float: left;
}
```
- Adding `.clearfix` to tags section:
```html
<section class="tags clearfix">
```

**Screenshots**
Tags underlined in blue can be clicked. Reds can't.
![imagen](https://user-images.githubusercontent.com/10481749/55675935-0f978a00-58c2-11e9-86f3-0850970baba6.png)

### Fixed:
![imagen](https://user-images.githubusercontent.com/10481749/55675945-4bcaea80-58c2-11e9-9d68-0e2de3f8074f.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Firefox
 - Version 66.0.2 64bits

**Comment by terrylinooo** [comment]
Thanks for reporting this issue. I have updated this theme to version 1.3.2
It will be updated on the WordPress theme dictionary soon.
