### ISSUE TITLE
Firefox: Sticky logo disappears while scrolling when sticky sidebar is present

### ISSUE THREAD

**Issue by hacheraw** [terrylinooo/mynote#9]
Yep, it's me again.

**Describe the bug**
In Firefox when sticky sidebar has any widget and you scroll the page, the logo disappears and it shows the word "Logo".
In Chrome it works as expected.

------------
### Edit:
this is weird. If while on a post I click "customize" it works properly. Then, I close "customize" and it keeps working properly until I push F5, then it breaks again 😮 
[Here is a video](https://notes.jorgeff.com/img/bug9.mp4)

------------

**To Reproduce**
1. Use Firefox
2. Ad a wiget to sidebar sticky
3. Scroll down/up

**Expected behavior**
Show image as usual.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/10481749/55676445-71a9bc80-58cd-11e9-9a17-27e60ad893cd.png)
![imagen](https://user-images.githubusercontent.com/10481749/55676382-2511b180-58cc-11e9-81e3-74d5d3d8e2d5.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Firefox
 - Version 66.0.2 64bits

**Additional context**
While scrolling, you can see in the *inspector* `<a class="navbar-brand">` and `<div id="progress-title">` changing all the time vía js. This may be the problem.
#### Firefox (orange means changes):
![imagen](https://user-images.githubusercontent.com/10481749/55676505-64410200-58ce-11e9-9751-1e133fff054c.png)
#### Chrome (purple means changes):
![imagen](https://user-images.githubusercontent.com/10481749/55676525-bda93100-58ce-11e9-84ad-9d699549f5fb.png)

**Comment by terrylinooo** [comment]
Thanks for your reporting clearly about this issue.
It is weird because I use Firefox and works as expected. I will try to reproduce this issue.

**Comment by hacheraw** [comment]
Thanks for your work.

**Update on the issue**: 
I've notice it works as expected the first time you enter to the post. If you push F5 or reload, then it crashes.
- I've disabled all my Firefox extensions
- Tried logged and logged out.
- Tried in private navigation

**Comment by terrylinooo** [comment]
I still not figure out this issue. I keep this issue opened to see if anyone else has the same problem.

**Comment by hacheraw** [comment]
This works now in **Firefox 84.0.2 (64-bit)**.
